### ISSUE TITLE
Alpha release checklist

### ISSUE THREAD

**Issue by SrIzan10** [SrIzan10/featheroom#1]
# 0.1-alpha Release Checklist

## Core Functionality
- [x] Make actual course cards on the home page https://github.com/SrIzan10/featheroom/commit/470743e942b0acb75406b27e92dd89f3fa04198e
- [x] Complete course work material viewer https://github.com/SrIzan10/featheroom/commit/022b8e85c8e25a5adda5abaa45da36ff18f9d438
- [ ] ~~Add grade viewing capability~~ postponed to later release
- [ ] ~~Use Android device's MD3 color selection by default~~ postponed to later release
- [ ] Confirm iOS platform support

## Infrastructure 
- [ ] ~~Switch from Firebase to direct Google Cloud auth~~ apparently users don't reflect in the authentication dashboard so yeah
- [x] Configure proper build settings in app.json

## Testing & Quality
- [ ] Use my own prettierrc config and run through the entire codebase

## Release
- [x] Create release workflow in GitHub Actions
- [x] Set up EAS update process
- [ ] Create alpha release tag
- [ ] Apply for Cider to get Testflight access
- [ ] Publish to F-Droid
